# Generated by Django 5.2.17 on 2026-08-27 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Fantasy', 'Fantasy'), ('Science', 'Science'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Other', 'Other')], max_length=20)),
                ('language', models.CharField(choices=[('Bulgarian', 'Bulgarian'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Other', 'Other')], max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('publishing_date', models.DateField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
